### ISSUE TITLE
Firefox missing `libharfbuzz.so.0`

### ISSUE THREAD

**Issue by WesleyAC** [ludios/nixos-playwright#4]
Thanks for making these scripts! It was super helpful to be able to get up and running with Playwright quickly without having to deal with too much NixOS stuff :)

I'm having a problem running Firefox — attached is the patch log and playwright error:

```
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/liblgpllibs.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/plugin-container
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libmozavcodec.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/gmp-clearkey/0.1/libclearkey.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libmozgtk.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libplc4.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libsoftokn3.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/updater
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libmozwayland.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libnss3.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libplds4.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libmozsqlite3.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libnspr4.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/firefox-bin
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libsmime3.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libssl3.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libnssutil3.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/pingsender
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libfreeblpriv3.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/firefox
patchelf: not an ELF executable
patchelf: not an ELF executable
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libnssckbi.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libmozavutil.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libxul.so
/home/wesleyac/.cache/ms-playwright/firefox-1297/firefox/libmozsandbox.so
```

```
  3) [firefox] › tests/e2e.spec.ts:19:1 › misc =====================================================

    browserType.launch: Host system is missing dependencies!

      Missing libraries are:
          libharfbuzz.so.0


        at Object._baseTest.extend.browser.scope [as fn] (/home/wesleyac/code/deeplinks/.yarn/cache/@playwright-test-npm-1.16.3-3b65662da1-363f2f214d.zip/node_modules/@playwright/test/lib/index.js:221:40)
        at Fixture.setup (/home/wesleyac/code/deeplinks/.yarn/cache/@playwright-test-npm-1.16.3-3b65662da1-363f2f214d.zip/node_modules/@playwright/test/lib/fixtures.js:74:73)
        at FixtureRunner.setupFixtureForRegistration (/home/wesleyac/code/deeplinks/.yarn/cache/@playwright-test-npm-1.16.3-3b65662da1-363f2f214d.zip/node_modules/@playwright/test/lib/fixtures.js:315:5)
        at Fixture.setup (/home/wesleyac/code/deeplinks/.yarn/cache/@playwright-test-npm-1.16.3-3b65662da1-363f2f214d.zip/node_modules/@playwright/test/lib/fixtures.js:58:19)
        at FixtureRunner.setupFixtureForRegistration (/home/wesleyac/code/deeplinks/.yarn/cache/@playwright-test-npm-1.16.3-3b65662da1-363f2f214d.zip/node_modules/@playwright/test/lib/fixtures.js:315:5)
        at Fixture.setup (/home/wesleyac/code/deeplinks/.yarn/cache/@playwright-test-npm-1.16.3-3b65662da1-363f2f214d.zip/node_modules/@playwright/test/lib/fixtures.js:58:19)
        at FixtureRunner.setupFixtureForRegistration (/home/wesleyac/code/deeplinks/.yarn/cache/@playwright-test-npm-1.16.3-3b65662da1-363f2f214d.zip/node_modules/@playwright/test/lib/fixtures.js:315:5)
        at FixtureRunner.resolveParametersAndRunHookOrTest (/home/wesleyac/code/deeplinks/.yarn/cache/@playwright-test-npm-1.16.3-3b65662da1-363f2f214d.zip/node_modules/@playwright/test/lib/fixtures.js:300:23)
        at WorkerRunner._runTestWithBeforeHooks (/home/wesleyac/code/deeplinks/.yarn/cache/@playwright-test-npm-1.16.3-3b65662da1-363f2f214d.zip/node_modules/@playwright/test/lib/workerRunner.js:478:7)
```

`which firefox` reports `/nix/store/dzd85wsi9wh00ndm5xazxgx6f7sdxxy1-firefox-bin-94.0.2/bin/firefox`. I'm using playwright version 1.16.3 (running it in node, using `@playwright/test`). I'm running on NixOS 21.05.

Strangely, running `~/.cache/ms-playwright/firefox-1297/firefox/firefox-bin` launches a instance of firefox that appears to work fine.

Let me know if you need any more info!

**Comment by WesleyAC** [comment]
Oh, and `ldd ~/.cache/ms-playwright/firefox-1297/firefox/firefox-bin` reports the following:

```
	linux-vdso.so.1 (0x00007fff90579000)
	libpthread.so.0 => /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libpthread.so.0 (0x00007f02ff5d6000)
	libdl.so.2 => /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libdl.so.2 (0x00007f02ff5d1000)
	libstdc++.so.6 => /nix/store/9w7ra0b2nqnbly4v64vwayml255lb9bp-gcc-10.3.0-lib/lib/libstdc++.so.6 (0x00007f02ff3fa000)
	libm.so.6 => /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libm.so.6 (0x00007f02ff2b7000)
	libgcc_s.so.1 => /nix/store/9w7ra0b2nqnbly4v64vwayml255lb9bp-gcc-10.3.0-lib/lib/libgcc_s.so.1 (0x00007f02ff29d000)
	libc.so.6 => /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libc.so.6 (0x00007f02ff0dc000)
	/nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/ld-linux-x86-64.so.2 => /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib64/ld-linux-x86-64.so.2 (0x00007f02ff6bd000)
```

**Comment by WesleyAC** [comment]
`cp /nix/store/klbfc76skpzs7z807kjppqlvkxsc0w34-harfbuzz-2.8.0/lib/libharfbuzz.so.0 ~/.cache/ms-playwright/firefox-1297/firefox/` is a dumb hack that seems to fix this, but I presume the real fix is for the harfbuzz dependency to be actually detected somewhere and `patchelf`ed in.

**Comment by ivan** [comment]
Thanks for the report. Are you reproducing this just by running the playwright tests, or by launching Firefox through playwright? I don't use playwright at the moment, but I would take a PR for this or happily transfer the repo over.

**Comment by WesleyAC** [comment]
I'm reproducing by running playwright tests — `yarn playwright test` in my case.

I'll look into making a PR for this at some point, and if I get that far would be happy to take over the repo.
